import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/components/AuthContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            
          >
            <AuthProvider>
        {/* <SidebarProvider > */}
      {/* <AppSidebar /> */}
      <main className="w-full">
        {/* <SidebarTrigger /> */}

            <div className="w-[100%]">
        <Navbar/>
            {children}

            </div>
      </main>
    {/* </SidebarProvider> */}
    </AuthProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
